### ISSUE TITLE
网线网速很快，但是ubuntu18网速很慢

### ISSUE THREAD

**Issue by henbucuoshanghai** [geerlingguy/docker-ubuntu1804-ansible#16]
求解释

**Comment by geerlingguy** [comment]
If possible, could you provide a rough English translation of this issue? All I can get is:

> The speed of the network cable is very fast, but the speed of ubuntu18 is very slow

Closing for now but feel free to reopen if you can provide more detail.

**Comment by henbucuoshanghai** [comment]
in ubuntu18,the speed of git is very slow,i want to git clone sth from github,but the speed is slow,how to solve it?

**Comment by geerlingguy** [comment]
That's something that I don't know if I'd be able to help with; I would suggest asking maybe on the Ubuntu answers site (https://askubuntu.com). There are a lot of different things that can affect Git performance, like disk speed, network speed (sometimes), and things like system wide file encryption.
