### ISSUE TITLE
No ssh ?

### ISSUE THREAD

**Issue by ceefour** [geerlingguy/docker-ubuntu1804-ansible#19]
I can't run ansible anything because ssh is not installed by default.

**Comment by geerlingguy** [comment]
@ceefour these containers are meant to be used either to test a playbook inside the container (e.g. have playbook in container, run it inside), or to be used with a `docker` connection—using SSH to connect to docker containers is not typically a good idea.

See documentation on connecting to Docker containers here: https://docs.ansible.com/ansible/latest/scenario_guides/guide_docker.html

Note that these containers are mainly useful for testing things inside Docker (for things like Molecule playbook, collection, and role testing).

**Comment by ceefour** [comment]
@geerlingguy I didn't want to ssh to the docker container.

What I meant is that the docker-ansible container (as controller) cannot connect/ssh to remote hosts being managed.
