### ISSUE TITLE
Getting few errors on build

### ISSUE THREAD

**Issue by spekki** [geerlingguy/docker-ubuntu1804-ansible#3]
I get errors,

Failed building wheel for ansible
Failed building wheel for PyYAML
Failed building wheel for MarkupSafe
Failed building wheel for pycparser

Fixed it though by adding 

`RUN pip install wheel `
before
`RUN pip install ansible`

**Comment by geerlingguy** [comment]
@spekki - Interesting; I haven't run into these issues last time I did a build, which was a few days ago (to get Ansible 2.7.0 on the container—see https://hub.docker.com/r/geerlingguy/docker-ubuntu1804-ansible/tags/). Are you making any modifications, or running `docker build` directly on this project's Dockerfile?

**Comment by spekki** [comment]
> @spekki - Interesting; I haven't run into these issues last time I did a build, which was a few days ago (to get Ansible 2.7.0 on the container—see https://hub.docker.com/r/geerlingguy/docker-ubuntu1804-ansible/tags/). Are you making any modifications, or running `docker build` directly on this project's Dockerfile?

Didn't do any modifications before that wheel installation line. No idea why it failed as i said, it's working now. Just leaving this here in case someone else bumps into the same problem.

**Comment by geerlingguy** [comment]
@spekki - I'll chalk it up to weird chance or networking :) Thanks for posting the update!
